# fly.toml app configuration file generated for digital-museum on 2025-10-07T12:46:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'digital-museum'
primary_region = 'cdg'
console_command = 'php /var/www/artisan tinker'

[experimental]
  auto_rollback = true

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[deploy]
  release_command = 'php artisan migrate --force'

[env]
  APP_ENV = 'production'
  APP_URL = 'https://digital-museum.fly.dev'
  DB_CONNECTION = 'pgsql'
  DB_DATABASE = 'digital_museum'
  DB_HOST = 'digital-museum-db.flycast'
  DB_PORT = '5432'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'
  SESSION_DOMAIN = 'digital-museum.fly.dev'
  SESSION_SAME_SITE = 'lax'
  SESSION_LIFETIME = '120'
  ASSET_URL = 'https://digital-museum.fly.dev'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'

  [[services.http_checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '1s'
    method = 'GET'
    path = '/health'
    protocol = 'http'
    tls_skip_verify = false

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/var/www/public'
  url_prefix = '/'
